version: '3'
 
services:
  vote_backend-service-node2:
    network_mode: host
    build: .
    depends_on:
      - redis
      - postgres

  redis:
    image: redis:latest
    ports:
      - "6379:6379" 

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - 'postgres:/var/lib/postgresql/data'

volumes:
    postgres: