package controller

import "vote_backend/models"

func ValidateVote(newVote models.Transaction) bool {
	// ensure that the txid is valid, and was generated by an official client app
	// ensure that the node id is valid
	// ensure that the candidate id is valid
	// ensure that the vote hash is valid
	// ensure that the voter exists and that the voters details hash matches the stored hash
	// ensure that the voter hasnt already voted
	// insert verified transaction into db

}
